const TelegramBot = require('node-telegram-bot-api');
const token = process.env.TELEGRAM_BOT_TOKEN;
const chatId = process.env.TELEGRAM_CHAT_ID;
let bot = token ? new TelegramBot(token, { polling: false }) : null;

async function sendReport(messageType = 'daily', content = '', metadata = {}) {
    if (!bot) return false;
    let message = messageType === 'daily' ? _buildDailyMessage(content, metadata) : _buildWeeklyMessage(content, metadata);
    try {
        await bot.sendMessage(chatId, message, { parse_mode: 'Markdown', disable_web_page_preview: true });
        return true;
    } catch (error) {
        console.error(`Error sending ${messageType} to Telegram:`, error.message);
        return false;
    }
}

function _stripHtmlTags(html) {
    return html ? html.replace(/<[^>]*>/g, '').replace(/\n\n+/g, '\n').trim() : '';
}

function _buildDailyMessage(content, metadata) {
    const today = new Date().toLocaleDateString('en-GB');
    const summary = _stripHtmlTags(content).substring(0, 500);
    return `📊 *Kash Daily Report* — ${today}\n\n${summary}\n\n👤 Sent to: ${metadata.userEmail}\n⏰ Generated by Kash AI`;
}

function _buildWeeklyMessage(content, metadata) {
    return `📈 *Kash Weekly Report*\n🗓️ ${metadata.startDate} to ${metadata.endDate}\n💰 Spent: ${metadata.totalSpent} TND\n⚠️ At Risk: ${metadata.budgetsAtRisk}\n🚨 Overdue: ${metadata.overduePayments}\n\n📝 Summary: ${metadata.aiSummary}\n\n👤 Sent to: ${metadata.userEmail}`;
}

module.exports = { sendReport };
