// services/dexo/report.service.js
//
// Dexo Report Service — Telegram notifications and report generation/formatting.
// Extracted from dexoService.js for separation of concerns.
//
// Responsibilities:
//   - Telegram bot initialization and message dispatch
//   - Daily and weekly report message formatting
//   - LLM-based daily report text generation from HeraActions
//
// Does NOT handle:
//   - Document processing (stays in dexoService.js)
//   - Strategic advice / onboarding (stays in dexoService.js)
//   - CEO briefing (stays in services/dexo/briefing.service.js)

const TelegramBot = require('node-telegram-bot-api');
const HeraAction = require('../../models/HeraAction');
const heraAgent = require('../hera.agent');

// ─── Telegram bot singleton ───────────────────────────────────────────────────
const telegramToken = process.env.TELEGRAM_BOT_TOKEN;
const telegramChatId = process.env.TELEGRAM_CHAT_ID;

const telegramBot = telegramToken
  ? new TelegramBot(telegramToken, { polling: false })
  : null;

// ─── Report generation ────────────────────────────────────────────────────────

/**
 * Generate a short LLM-based daily report from recent HeraActions.
 * Used internally by cron jobs and autonomous services.
 *
 * @param {string|null} ceoId - CEO user ID. If null, queries all actions.
 * @returns {Promise<string>} Plain-text report string.
 */
async function generateDailyReport(ceoId) {
  const query = ceoId ? { ceo_id: ceoId } : {};

  const actions = await HeraAction.find(query)
    .sort({ created_at: -1 })
    .limit(10)
    .populate('employee_id');

  if (actions.length === 0) return '🏢 Statut : Calme.';

  const summary = actions
    .map(
      (a) =>
        `- ${a.action_type} pour ${a.employee_id?.name || 'Système'}`
    )
    .join('\n');

  const aiResponse = await heraAgent.llm.invoke(
    `Tu es Dexo. Rédige un briefing très court pour le CEO : ${summary}`
  );

  return aiResponse.content;
}

// ─── Telegram dispatch ────────────────────────────────────────────────────────

/**
 * Send a report message to the configured Telegram chat.
 *
 * @param {'daily'|'weekly'} messageType
 * @param {string} content - Raw report content (may contain HTML).
 * @param {object} metadata - Extra data used by message builders.
 * @returns {Promise<boolean>} true if sent successfully, false otherwise.
 */
async function sendReport(messageType = 'daily', content = '', metadata = {}) {
  if (!telegramBot || !telegramChatId) {
    console.warn('⚠️ Telegram non configuré pour Dexo report');
    return false;
  }

  const message =
    messageType === 'daily'
      ? _buildDailyMessage(content, metadata)
      : _buildWeeklyMessage(content, metadata);

  try {
    await telegramBot.sendMessage(telegramChatId, message, {
      disable_web_page_preview: true,
    });

    console.log(`✅ Dexo ${messageType} report envoyé sur Telegram`);
    return true;
  } catch (error) {
    console.error(
      `❌ Error sending ${messageType} report to Telegram:`,
      error.message
    );
    return false;
  }
}

// ─── Message formatters ───────────────────────────────────────────────────────

/**
 * Strip HTML tags from a string and collapse excess whitespace.
 * Used before sending content to Telegram (plain-text only).
 *
 * @param {string} html
 * @returns {string}
 */
function _stripHtmlTags(html) {
  return html
    ? html.replace(/<[^>]*>/g, '').replace(/\n\n+/g, '\n').trim()
    : '';
}

/**
 * Build the daily Telegram message string.
 *
 * @param {string} content - Report body (may contain HTML).
 * @param {object} metadata
 * @param {string} [metadata.userEmail]
 * @returns {string}
 */
function _buildDailyMessage(content, metadata) {
  const today = new Date().toLocaleDateString('en-GB');
  const summary = _stripHtmlTags(content).substring(0, 500);

  return `📊 Kash Daily Report — ${today}

${summary}

👤 Sent to: ${metadata.userEmail || 'CEO'}
⏰ Generated by Kash AI`;
}

/**
 * Build the weekly Telegram message string.
 *
 * @param {string} _content - Unused for weekly (kept for API symmetry with daily).
 * @param {object} metadata
 * @param {string} [metadata.startDate]
 * @param {string} [metadata.endDate]
 * @param {number} [metadata.totalSpent]
 * @param {number} [metadata.budgetsAtRisk]
 * @param {number} [metadata.overduePayments]
 * @param {string} [metadata.aiSummary]
 * @param {string} [metadata.userEmail]
 * @returns {string}
 */
function _buildWeeklyMessage(_content, metadata) {
  return `📈 Kash Weekly Report

🗓️ ${metadata.startDate} → ${metadata.endDate}
💰 Dépenses : ${metadata.totalSpent} TND
⚠️ Budgets à risque : ${metadata.budgetsAtRisk}
🚨 Paiements en retard : ${metadata.overduePayments}

📝 Résumé :
${metadata.aiSummary}

👤 Sent to: ${metadata.userEmail || 'CEO'}`;
}

// ─── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
  generateDailyReport,
  sendReport,
  // Exported for unit testing and direct use by cron jobs
  _buildDailyMessage,
  _buildWeeklyMessage,
  _stripHtmlTags,
};
